import type { Metadata } from "next";
import "./globals.scss";
import getMobile from "../functions/detect_phone";
import PhoneNavbar from "../components/layout/navbars/phone_navbar";
import PcNavbar from "../components/layout/navbars/pc_navbar";
import Footer from "@/components/layout/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
          <script src="https://unpkg.com/phosphor-icons"></script>
          <link rel="preconnect" href="https://fonts.googleapis.com"/>
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous"/>
          <link href="https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400..700;1,400..700&family=PT+Serif:ital,wght@0,400;0,700;1,400;1,700&family=Playfair+Display:ital,wght@0,400..900;1,400..900&display=swap" rel="stylesheet"/>
        </head>
      <body
        className={`antialiased flex flex-col w-[100vw] h-[100vh] overflow-hidden`}>
        {getMobile() ? <PhoneNavbar/> : <PcNavbar/>}
        <div className="w-full flex-grow overflow-y-scroll">
          <div className="min-h-[100vh] overflow-x-hidden">
              {children}
          </div>
          <Footer/>
        </div>
      </body>
    </html>
  );
}
